apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-demo-project
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-demo-project
    server: "https://kubernetes.default.svc"
  project: demo-project
  source: 
    path: guestbook
    repoURL: 'https://github.com/amkac/argocd-samples.git'
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true